[profile.default]
src = "src"
test = "test"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 1000000
remappings = ["@solidity/=src/",  '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/' ]
fs_permissions = [{ access = "read-write", path = "./" }]
#via_ir=true, totally collapse the performances, stack not optimized when activated
